### PR TITLE
Adds "snap to border" functionality

### PR DESCRIPTION
**Pull request by Tantun**
Recognizes a rectangular area inside the selected region and automatically snaps the screenshot selection
Feature activated by right click selection or pressing space (also toggles "snap selection")
Added new menu entry to enable "snapping" outside the selected region

See it in action https://www.youtube.com/watch?v=Y4Gb7NgOPLI&t

### CODE REVIEW

**Comment by jleclanche** [comment]
That is a seriously cool feature.

**Comment by agaida** [comment]
yes, full ack.

**Comment by stefonarch** [comment]
Very nice feature indeed, it needs a right click to snap, true?
But I have  an issue with the  "stamp" shortcut: it does work only the first time when screengrab is not in execution.

**Comment by Tantun** [comment]
Thanks everybody.

Yes the "snap" is activated automatically when doing region selection with the right button ("snap" is performed as soon as the right button is released), but pressing space key will toggle between the user marked region and the snapped region. Doing the usual left button region selection, snap is not activated automatically when the button is released, but it can be activated by pressing the space key. After that, space key again toggles the selection between the user marked region and the snapped region.

To summarize:
- Left mouse button, Enter key and Escape key work as before;
- Right mouse button wasn't functional before, here it is used in the same way as the left mouse button, just the "snap" is activated immediately when the button is released
- Space key wasn't functional before, here it is used to toggle the selection between the user marked region and the snapped region

I'm not sure what you mean by the "stamp" shortcut.

Also just to mention her that this also introduces a new menu entry to allow for "snapping" a little bit outside the marked region (so the user doesn't have to completely mark the rectangle). When true, the algorithm is a little bit different, as in this case it will snap each side to the line with the highest average pixel gradient (which is probably the most natural in this case). Normally, it stops searching for the line when the high gradient drop occurs. This seems to behave more predictable, so by default snapping outside the marked region is disabled.

**Comment by stefonarch** [comment]
> I'm not sure what you mean by the "stamp" shortcut.

Default key for "new" is the stamp (print) key, behavior is buggy now as described above, the shortkey (sorry not shortcut...) works only for the first time, when screengrab is closed, once it  sits in the system tray it looks like trying opening new instance (icon is moving to free new  place a moment) but does not do anything.

**Comment by jleclanche** [comment]
Any objections to merging this as is? @agaida ?

**Comment by agaida** [comment]
no, not really

**Pull request merged**
